// =====================================================
// AVB GestÃ£o de Demandas â€” Dados Reais ExtraÃ­dos
// =====================================================

const DEFAULT_USERS = [
  { id: 1, username: 'admin', password: 'av&b123', role: 'admin', name: 'Administrador AVB', approved: true },
  { id: 2, username: 'gestor', password: 'avb@2026', role: 'gestor', name: 'Gestor de Demandas', approved: true },
  { id: 3, username: 'viewer', password: 'avb@2026', role: 'viewer', name: 'Visualizador', approved: true }
];

const SAMPLE_DEMANDAS = [
    {
        "dataPrevista":  "07/01/26",
        "atividades":  "Testar todos os itens comprados",
        "id":  1,
        "status":  "Concluído",
        "assunto":  "FX2",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Única coisa que não foi testada é o conversor (garantia). Câmeras, fontes, cabos e lentes foram testados"
    },
    {
        "dataPrevista":  "09/01/26",
        "atividades":  "Testar a FX2 aqui no estúdio 5",
        "id":  2,
        "status":  "Concluído",
        "assunto":  "FX2",
        "area":  "Estúdios presenciais",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "10/02/26",
        "atividades":  "Realizar teste comparativo FX2 x Black Magic com time do Mudo",
        "id":  3,
        "status":  "Concluído",
        "assunto":  "FX2",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Aguardando retorno do Mudo sobre a data que virão"
    },
    {
        "dataPrevista":  "18/02/26",
        "atividades":  "Preparar material de apresentação do comparativo FX2 x Black Magic",
        "id":  4,
        "status":  "Cancelado",
        "assunto":  "FX2",
        "area":  "Estúdios presenciais",
        "responsavel":  "Rodrigo",
        "observacoes":  "Será preparado pelo Mudo"
    },
    {
        "dataPrevista":  "10/02/26",
        "atividades":  "Criar cronograma detalhado para a alteração dos equipamentos dos estúdios presenciais",
        "id":  5,
        "status":  "Concluído",
        "assunto":  "FX2",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Dependência da definição da câmera"
    },
    {
        "dataPrevista":  "20/03/26",
        "atividades":  "Criação do Padrão Gran usando os itens novos - Presenciais",
        "id":  6,
        "status":  "Concluído",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "https://docs.google.com/document/d/1I4wiKeGyq4l2Tu11MQTqg_yZpZ6qPXemU2-8WhLbf1I/edit?usp=sharing"
    },
    {
        "dataPrevista":  "15/05/26",
        "atividades":  "Elaborar POP para cumprir esse Padrão Gran - Operacional\n\nFazer com atualização do modelo 2x1 - Verificar com Walisson",
        "id":  7,
        "status":  "Em andamento",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "Versão inicial ainda está com estilo de Manual - fazer POP com mais cara de POP"
    },
    {
        "dataPrevista":  "27/03/26",
        "atividades":  "Elaborar POP para cumprir esse Padrão Gran - Técnico",
        "id":  8,
        "status":  "Concluído",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Qualidade",
        "responsavel":  "André",
        "observacoes":  "Foi elaborado um documento único para Operacional e Técnico"
    },
    {
        "dataPrevista":  "07/05/26",
        "atividades":  "Adequação Geral dos HS Gran - Lista com todas as necessidades de forma objetiva, assertiva e considerando docentes de pé",
        "id":  9,
        "status":  "Em andamento",
        "assunto":  "Padrão Gran Home",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "Não será entregue 100% em razão de faltarem docentes para colhermos os dados, mas dia 07/05 teremos a visualização em dashboard."
    },
    {
        "dataPrevista":  "09/03/26",
        "atividades":  "Criar cronograma de implementação do Padrão Gran",
        "id":  10,
        "status":  "Concluído",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Teste câmera Calado (Venuslive V2)",
        "id":  11,
        "status":  "Cancelado",
        "assunto":  "Câmera Calado Venuslive V2",
        "area":  "Home",
        "responsavel":  "Pryscilla",
        "observacoes":  "Aguardando retorno Vivian - Não avaliaremos por enquanto"
    },
    {
        "dataPrevista":  "09/01/26",
        "atividades":  "Aprender a mexer na câmera do Calado (Venuslive Air)",
        "id":  12,
        "status":  "Concluído",
        "assunto":  "Câmera Calado Venuslive Air",
        "area":  "Home",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "13/01/26",
        "atividades":  "Teste câmera Calado (Venuslive Air)",
        "id":  13,
        "status":  "Concluído",
        "assunto":  "Câmera Calado Venuslive Air",
        "area":  "Home",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "16/01/26",
        "atividades":  "Teste em casa (cenário real)",
        "id":  14,
        "status":  "Concluído",
        "assunto":  "Câmera Calado Venuslive Air",
        "area":  "Home",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "16/01/26",
        "atividades":  "Entrega do material com o resultado",
        "id":  15,
        "status":  "Concluído",
        "assunto":  "Câmera Calado Venuslive Air",
        "area":  "Home",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "06/03/26",
        "atividades":  "3 docentes no Padrão Gran Home",
        "id":  16,
        "status":  "Concluído",
        "assunto":  "Padrão Gran Home",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "Conseguimos fazer com 4 docentes"
    },
    {
        "dataPrevista":  "15/05/26",
        "atividades":  "Criar fundo de \"continuação\" para segunda câmera do estúdio 3",
        "id":  17,
        "status":  "Em andamento",
        "assunto":  "Qualidade",
        "area":  "Estúdios presenciais",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Criação do Padrão Gran Home",
        "id":  18,
        "status":  "Em andamento",
        "assunto":  "Padrão Gran Home",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "1ª apresentação dos requisitos mínimos e plano de ação: 22/01\nApresentar Mosaico para Vivian: 27/01\nApresentação para Vivian com ajustes e cronogramas finais: 07/04"
    },
    {
        "dataPrevista":  "",
        "atividades":  "Apresentar para Vivian Padrão Gran Home",
        "id":  19,
        "status":  "Em andamento",
        "assunto":  "Padrão Gran Home",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Elaborar POP para o Padrão Gran Home",
        "id":  20,
        "status":  "Em andamento",
        "assunto":  "Padrão Gran Home",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "Faremos em conjunto, qualidade + líder HS"
    },
    {
        "dataPrevista":  "",
        "atividades":  "Criar cronograma para implementação do Padrão Gran Home",
        "id":  21,
        "status":  "",
        "assunto":  "Padrão Gran Home",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "Faseado"
    },
    {
        "dataPrevista":  "27/02/2026",
        "atividades":  "Analisar e encaminhar para reedição ou regravação dos blocos referentes às 25 avaliações negativas relacionadas a quesitos técnicos.",
        "id":  22,
        "status":  "Concluído",
        "assunto":  "Avaliações negativas - Prof Fernando Maciel",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "Problemas identificados e encaminhados para suas resoluções possíveis junto a editores.agora, finalizaremos logo."
    },
    {
        "dataPrevista":  "08/01/26",
        "atividades":  "Enviar ao Mudo o orçamento do mega estúdio, sem os valores do Zeus",
        "id":  23,
        "status":  "Concluído",
        "assunto":  "Mega estúdio",
        "area":  "Estúdios presenciais",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "13/01/26",
        "atividades":  "Reunião com Mudo para apontamentos do orçamento - Agendada para: 13/01",
        "id":  24,
        "status":  "Concluído",
        "assunto":  "Mega estúdio",
        "area":  "Estúdios presenciais",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "13/01/26",
        "atividades":  "Propor alteração no projeto do mega estúdio ao John (ADM-arquitetura) - Objetivo: ampliar o Mega\nProposta 1: Retirar 1 estúdio e manter 2\nProposta 2: Retirar os 3 estúdios e no final deixar um espaço \"lounge\"",
        "id":  25,
        "status":  "Concluído",
        "assunto":  "Mega estúdio",
        "area":  "Estúdios presenciais",
        "responsavel":  "Pryscilla",
        "observacoes":  "Decidimos por seguir com a Proposta 2 (sem estúdios), porém empresa de arquitetura tentará acomodar melhor as demais salas"
    },
    {
        "dataPrevista":  "19/01/26",
        "atividades":  "Mudo retornar com avaliação da planta do mega estúdio",
        "id":  26,
        "status":  "Concluído",
        "assunto":  "Mega estúdio",
        "area":  "Estúdios presenciais",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "15/04/26",
        "atividades":  "Mudo retornar com avaliação dos equipamentos do mega estúdio",
        "id":  27,
        "status":  "Concluído",
        "assunto":  "Mega estúdio",
        "area":  "Estúdios presenciais",
        "responsavel":  "Pryscilla",
        "observacoes":  "Previsão de entrega em Abril"
    },
    {
        "dataPrevista":  "10/02/26",
        "atividades":  "Mudo enviar alguém para testar FX2 e Black Magic para estúdios presenciais e mega estúdio",
        "id":  28,
        "status":  "Concluído",
        "assunto":  "Mega estúdio",
        "area":  "Estúdios presenciais",
        "responsavel":  "Pryscilla",
        "observacoes":  "16/01 - Falei com Mudo e ainda está tentando alguém para vir aqui"
    },
    {
        "dataPrevista":  "10/02/26",
        "atividades":  "Testar Black Magic para mega estúdio",
        "id":  29,
        "status":  "Concluído",
        "assunto":  "Mega estúdio",
        "area":  "Estúdios presenciais",
        "responsavel":  "Pryscilla",
        "observacoes":  "Teste foi realizado, estamos aguardando o relatório do Mudo"
    },
    {
        "dataPrevista":  "08/01/26",
        "atividades":  "Gastos extras - Concluir com o financeiro",
        "id":  30,
        "status":  "Concluído",
        "assunto":  "Reinvenção",
        "area":  "Reinvenção",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "21/01/26",
        "atividades":  "Retrabalhos de OSs que não são registradas no dashboard",
        "id":  31,
        "status":  "Atrasado",
        "assunto":  "Dashboard",
        "area":  "Estúdios presenciais",
        "responsavel":  "Pedro",
        "observacoes":  "Verificar com Digão se está puxando do local correto\nNova data: 27/01 - 02/03 - 20/03 - Pedro Informou que não está tendo tempo de verificar."
    },
    {
        "dataPrevista":  "23/01/26",
        "atividades":  "Criar métricas para área externa",
        "id":  32,
        "status":  "Atrasado",
        "assunto":  "Dashboard",
        "area":  "Externo",
        "responsavel":  "Pedro",
        "observacoes":  "Walisson e Pedro detalharem demanda para o Saturno\nNova data: 06/02 - 31/03, o Pedro sinalizou que está fazendo o levantamento das melhorias geral do saturno, mas até o momento sem prazo(20/04)."
    },
    {
        "dataPrevista":  "20/01/26",
        "atividades":  "Mudo concluir orçamento de Vitória",
        "id":  33,
        "status":  "Concluído",
        "assunto":  "Gran Dicas Vitória",
        "area":  "Externo",
        "responsavel":  "Walisson",
        "observacoes":  "Evento acontecerá de 30/01 a 02/02.\nMudo está ajustando o orçamento. Inicial: 46,9k com nota e pagamento para 30 dias\nOrçamento New Events: 29K. As coisas não tem marca de nada, o painel é um P4 (Mudo trabalha com P2), tripés de câmera de 20Kgs a empresa não tem, é uma empresa bem simples e o material todo feito por eles.\nOrçamento final de Vitória (Lg7): R$57.348,00"
    },
    {
        "dataPrevista":  "19/01/26",
        "atividades":  "Definir quem irá ao evento",
        "id":  34,
        "status":  "Concluído",
        "assunto":  "Gran Dicas Vitória",
        "area":  "Externo",
        "responsavel":  "Walisson",
        "observacoes":  "Walisson, André, Espiga e Vitor Freitas"
    },
    {
        "dataPrevista":  "19/01/26",
        "atividades":  "Comprar passagens e hospedagens dos que irão ao evento",
        "id":  35,
        "status":  "Concluído",
        "assunto":  "Gran Dicas Vitória",
        "area":  "Externo",
        "responsavel":  "Walisson",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Viabilizar as avaliações de qualidade dentro do Saturno",
        "id":  36,
        "status":  "",
        "assunto":  "Saturno",
        "area":  "Qualidade",
        "responsavel":  "Pedro",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Automatizar elaboração da grade",
        "id":  37,
        "status":  "",
        "assunto":  "Automatização grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  "Após automatização do agendamento"
    },
    {
        "dataPrevista":  "16/01/26",
        "atividades":  "Organização da sobreloja - Sede",
        "id":  38,
        "status":  "Concluído",
        "assunto":  "Estrutural",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "06/02/26",
        "atividades":  "Organização do Estúdio 1",
        "id":  39,
        "status":  "Concluído",
        "assunto":  "Estrutural",
        "area":  "Estúdios presenciais",
        "responsavel":  "Digão",
        "observacoes":  "Data após a conclusão da retirada das portas"
    },
    {
        "dataPrevista":  "19/01/26",
        "atividades":  "Compra do microfone podcast: Ver com o time de eventos quais outros tipos de programas estão sendo considerados para o ano",
        "id":  40,
        "status":  "Concluído",
        "assunto":  "Estrutural",
        "area":  "Estúdios presenciais",
        "responsavel":  "Digão",
        "observacoes":  "Novo evento da Juliana Gebrim - Toda terça - Não tem previsão de acabar - Toda semana serão 3 pessoas"
    },
    {
        "dataPrevista":  "18/02/26",
        "atividades":  "Compra do microfone podcast: Conversar com o Mudo e ver se ele entende de podcast ou se conhece quem entenda, para checar se esse realmente é o melhor microfone",
        "id":  41,
        "status":  "Concluído",
        "assunto":  "Estrutural",
        "area":  "Estúdios presenciais",
        "responsavel":  "Digão",
        "observacoes":  "Mudo ficou de pesquisar e não retornou ainda - Não vamos aguardar, seguiremos com a compra do nosso microfone que é o melhor atualmente"
    },
    {
        "dataPrevista":  "20/03/26",
        "atividades":  "Compra do microfone podcast (1) - Com tripé",
        "id":  42,
        "status":  "Concluído",
        "assunto":  "Estrutural",
        "area":  "Estúdios presenciais",
        "responsavel":  "Digão",
        "observacoes":  "Para atender podcast (outro de backup compraremos em outro momento)\nCusto (microfone): 5000 (Shure)"
    },
    {
        "dataPrevista":  "24/04/26",
        "atividades":  "Novos computadores Vmix Home Studio",
        "id":  43,
        "status":  "Atrasado",
        "assunto":  "Troca computadores VMix",
        "area":  "Home",
        "responsavel":  "Costinha",
        "observacoes":  "Temos orçamento para troca de 30 notebooks VMix para Kit Home\nAguardando levantamento com os professores.\nVamos fazer a troca de 15 computadores sendo 8 em abril e 7 em maio. TI confirmou que seguiremos com os mesmos computadores que os comprados anteriormente, mesmo apresentando alguns problemas relatados.\n13/04 - Estamos aguardando o retorno de TI sobre o computador que usaremos. Além disso, estamos aguardando a definição do Pedagógico sobre os professores que permanecerão com Kit Gran.\nAlteramos também a troca para 8 em maio e 7 em junho.\nCostinha: enviar uma cronologia dos contatos com TI aguardando a definição do note."
    },
    {
        "dataPrevista":  "15/01/26",
        "atividades":  "Comunicar ao Mudo sobre a data de 25/02 e solicitar orçamento",
        "id":  44,
        "status":  "Concluído",
        "assunto":  "Aula Magna Fevereiro",
        "area":  "Externo",
        "responsavel":  "Walisson",
        "observacoes":  "Evento presencial que faremos na Gran Faculdade em 25/02 (Curitiba)\nTratar como Gran Dicas"
    },
    {
        "dataPrevista":  "13/02/26",
        "atividades":  "Mudo retornar com o orçamento (Curitiba)",
        "id":  45,
        "status":  "Concluído",
        "assunto":  "Aula Magna Fevereiro",
        "area":  "Externo",
        "responsavel":  "Walisson",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "13/02/26",
        "atividades":  "Definir quem irá ao evento",
        "id":  46,
        "status":  "Concluído",
        "assunto":  "Aula Magna Fevereiro",
        "area":  "Externo",
        "responsavel":  "Walisson",
        "observacoes":  "Orçamento apenas para 2 pessoas"
    },
    {
        "dataPrevista":  "30/01/26",
        "atividades":  "Comprar passagens e hospedagens dos que irão ao evento",
        "id":  47,
        "status":  "Concluído",
        "assunto":  "Aula Magna Fevereiro",
        "area":  "Externo",
        "responsavel":  "Walisson",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "20/01/26",
        "atividades":  "Conhecer funcionamento do GC (migração do Sigeco) com TI (Jordan Fernandes)",
        "id":  48,
        "status":  "Concluído",
        "assunto":  "Migração Sigeco",
        "area":  "Upload",
        "responsavel":  "Filipe",
        "observacoes":  "Assistentes de edição: Vitor Melo e Messias de Menezes\nO sistema novo GC é maravilhoso, mais moderno, intuitivo, corrige os bugs e erros, múltiplos uploads e carrossel. \nJordan vai levar para Lindal sobre a limitação do tamanho do arquivo que temos hoje (2GB) que teríamos que aumentar, vão conversar com o pessoal da Infra."
    },
    {
        "dataPrevista":  "09/03/26",
        "atividades":  "Realizar testes da migração do Sigeco para GC com TI (Jordan Fernandes)",
        "id":  49,
        "status":  "Concluído",
        "assunto":  "Migração Sigeco",
        "area":  "Upload",
        "responsavel":  "Filipe",
        "observacoes":  "Testes iniciais acontecerão com a Coord. Pedagógica e depois com a gente, e vamos começar pelos vídeos de Graduação. Inicio de testes com a gente é para o meio de fevereiro.\nTestes iniciais deram certo! Sistema é muito melhor, e agora expandiremos os testes.\nGraduação já estamos usando o GC, para preparatório ainda não há previsão de uso."
    },
    {
        "dataPrevista":  "19/01/26",
        "atividades":  "Solicitar ao time as dores do Saturno - o que gostariam que tivesse",
        "id":  50,
        "status":  "Concluído",
        "assunto":  "Saturno",
        "area":  "Liderança",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "13/04/26",
        "atividades":  "Reunir as dores do Saturno do time (AS IS/ TO BE)",
        "id":  51,
        "status":  "Concluído",
        "assunto":  "Saturno",
        "area":  "Liderança",
        "responsavel":  "Pedro",
        "observacoes":  "Redesenhar todo o fluxo"
    },
    {
        "dataPrevista":  "",
        "atividades":  "Criar plano de reconhecimento (quais áreas incluir? como será? premiação mensal?)+",
        "id":  52,
        "status":  "Em análise",
        "assunto":  "Pessoas",
        "area":  "Liderança",
        "responsavel":  "Pryscilla",
        "observacoes":  "Vamos avaliar na pesquisa Pulso o que é mais relevante para os nossos operadores"
    },
    {
        "dataPrevista":  "20/01/26",
        "atividades":  "Contatar professores críticos para entender possíveis problemas como: não subida da aula no drive",
        "id":  53,
        "status":  "Concluído",
        "assunto":  "Professores",
        "area":  "Pós produção",
        "responsavel":  "Filipe",
        "observacoes":  "Todos os professores informaram que terão mais atenção com esse problema. Um dos professores indicou que grava em um estúdio externo e que o estúdio informou que não pode salvar o vídeo no computador. Informamos ao pedagógico e ficaram de entender o problema com o estúdio."
    },
    {
        "dataPrevista":  "23/02/26",
        "atividades":  "Verificar porque os operadores não estão marcando se o professor está usando uniforme ou não",
        "id":  54,
        "status":  "Concluído",
        "assunto":  "Professores",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Digão: OK\nWalisson / Rogério: OK\nCostinha: OK"
    },
    {
        "dataPrevista":  "19/01/26",
        "atividades":  "Combinar com os times externos 1 reunião presencial por mês, inicialmente",
        "id":  55,
        "status":  "Concluído",
        "assunto":  "Reuniões",
        "area":  "Liderança",
        "responsavel":  "Filipe, Costinha e Rodrigo",
        "observacoes":  "Pós-Produção: 27/01\nHome: avaliar\nQualidade: "
    },
    {
        "dataPrevista":  "30/01/26",
        "atividades":  "Levantar quantos professores HOME precisariam de um HD por falta de espaço no computador. Cotar o HD",
        "id":  56,
        "status":  "Concluído",
        "assunto":  "Home",
        "area":  "Pós produção",
        "responsavel":  "Costinha",
        "observacoes":  "Professores arrumaram espaço"
    },
    {
        "dataPrevista":  "30/01/26",
        "atividades":  "Realizar reciclagem com os operadores (Incluir acompanhamento da transmissão pelo YouTube (visão do aluno e estúdio), uso do uniforme, padrões de audio e enquadramento)",
        "id":  57,
        "status":  "Concluído",
        "assunto":  "Operação",
        "area":  "Estúdios presenciais",
        "responsavel":  "Digão",
        "observacoes":  "Presencial: 30/01/26 (Encaminhamento do POP)\nHome: 26/01/26"
    },
    {
        "dataPrevista":  "",
        "atividades":  "Levantar as necessidades para colocar o estúdio 1 para funcionar",
        "id":  58,
        "status":  "Em análise",
        "assunto":  "Estrutural",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Cotamos um projeto novo com a empresa Cenarea.\nPara reativar o estúdio \"como está\" sem fazer um novo projeto de arquitetura precisamos comprar bancada e cadeiras (John chegou a fazer propostas de layout). Temos todos os equipamentos, computador, iluminação, novos.\nImportante também fazer reforma/ adesivar no fundo que está quebrado."
    },
    {
        "dataPrevista":  "19/01/26",
        "atividades":  "Comunicar ao time sobre pesquisa IFT (última semana de Janeiro)",
        "id":  59,
        "status":  "Concluído",
        "assunto":  "Pessoas",
        "area":  "Liderança",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "23/01/26",
        "atividades":  "Troca da porta estúdio 7",
        "id":  60,
        "status":  "Concluído",
        "assunto":  "Estrutural",
        "area":  "Estúdios presenciais",
        "responsavel":  "Digão",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "30/01/26",
        "atividades":  "Troca da porta estúdio 8",
        "id":  61,
        "status":  "Concluído",
        "assunto":  "Estrutural",
        "area":  "Estúdios presenciais",
        "responsavel":  "Digão",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "06/02/26",
        "atividades":  "Troca da porta estúdios 4 e 9",
        "id":  62,
        "status":  "Concluído",
        "assunto":  "Estrutural",
        "area":  "Estúdios presenciais",
        "responsavel":  "Digão",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "30/04/26",
        "atividades":  "Controle dos equipamentos de Home - SnipeIT",
        "id":  63,
        "status":  "Em andamento",
        "assunto":  "Estrutural",
        "area":  "Home",
        "responsavel":  "Walisson",
        "observacoes":  "Foi criado Forms para que os professores preencham com os equipamentos que possuem.\nFaremos após as informações que estão sendo recolhidas com o time do Rodrigo e Externa."
    },
    {
        "dataPrevista":  "18/02/26",
        "atividades":  "Reunião de fechamento - Feedback",
        "id":  64,
        "status":  "Concluído",
        "assunto":  "Pessoas",
        "area":  "Liderança",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Avaliar viabilidade e necessidade de padronizar o preset pra cada professor",
        "id":  65,
        "status":  "",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Estúdios presenciais",
        "responsavel":  "Rodrigo",
        "observacoes":  "A longo prazo"
    },
    {
        "dataPrevista":  "22/01/26",
        "atividades":  "Cronograma Mega Estúdio - Fechar com o John",
        "id":  66,
        "status":  "Concluído",
        "assunto":  "Mega estúdio",
        "area":  "Estúdios presenciais",
        "responsavel":  "Pryscilla",
        "observacoes":  "Agendado para 22/01"
    },
    {
        "dataPrevista":  "23/01/26",
        "atividades":  "Trocar todas as máquinas do vMix",
        "id":  67,
        "status":  "Concluído",
        "assunto":  "Equipamentos",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Todas as novas máquinas montadas, exceto o vMix 2 do Estúdio 12. Mudança do estúdio 12 será em 04/02. Do estúdio 10 será utilizado a atual do 12."
    },
    {
        "dataPrevista":  "30/01/26",
        "atividades":  "Fazer vídeo teste com a FX2",
        "id":  68,
        "status":  "Concluído",
        "assunto":  "FX2",
        "area":  "Estúdios presenciais",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "30/01/26",
        "atividades":  "Fazer upload do vídeo teste e avaliar os dados",
        "id":  69,
        "status":  "Concluído",
        "assunto":  "FX2",
        "area":  "Estúdios presenciais",
        "responsavel":  "Filipe",
        "observacoes":  "Teste deu certo!"
    },
    {
        "dataPrevista":  "",
        "atividades":  "Agendar com André (Ensino Superior) para apresentar as oportunidades de inovação",
        "id":  70,
        "status":  "Pausado",
        "assunto":  "Inovação",
        "area":  "Edição",
        "responsavel":  "Filipe",
        "observacoes":  "Com a reestruturação do setor e do Gran, esse projeto está pausado."
    },
    {
        "dataPrevista":  "",
        "atividades":  "Após desenvolvimento do Padrão Gran, criar métricas para medir o sucesso (ex.: % de aulas HS reprovadas por áudio, vídeo ou cenário)",
        "id":  71,
        "status":  "",
        "assunto":  "Padrão Gran",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "Nova análise de qualidade"
    },
    {
        "dataPrevista":  "11/02/26",
        "atividades":  "Instalar câmeras nos estúdios 3 (2 câmeras), 4, 5 e 6",
        "id":  72,
        "status":  "Concluído",
        "assunto":  "FX2",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Realizado no dia do treinamento com Pow e Vitor"
    },
    {
        "dataPrevista":  "12/02/26",
        "atividades":  "Ajustar o fundo do chroma de acordo com a nova iluminação do adesivo",
        "id":  73,
        "status":  "Concluído",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "André"
    },
    {
        "dataPrevista":  "03/03/26",
        "atividades":  "Instalação das câmeras nos demais estúdios (2, 7, 8, 9 e 11)",
        "id":  74,
        "status":  "Concluído",
        "assunto":  "FX2",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "André"
    },
    {
        "dataPrevista":  "20/03/26",
        "atividades":  "Criar documento escrito para operação (o que e por que)",
        "id":  75,
        "status":  "Concluído",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Estúdios presenciais",
        "responsavel":  "André",
        "observacoes":  "POP"
    },
    {
        "dataPrevista":  "30/03/26",
        "atividades":  "Treinar o time operacional",
        "id":  76,
        "status":  "Concluído",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Estúdios presenciais",
        "responsavel":  "Rodrigo",
        "observacoes":  "Técnico (André) + Padrão Gran (Rodrigo)"
    },
    {
        "dataPrevista":  "23/02/26",
        "atividades":  "Testar o PCloud",
        "id":  77,
        "status":  "Cancelado",
        "assunto":  "Professor não envia vídeo",
        "area":  "Edição",
        "responsavel":  "Filipe",
        "observacoes":  "O Google Drive atende o que precisamos."
    },
    {
        "dataPrevista":  "09/03/26",
        "atividades":  "Testar o Google Drive",
        "id":  78,
        "status":  "Concluído",
        "assunto":  "Professor não envia vídeo",
        "area":  "Edição",
        "responsavel":  "Filipe",
        "observacoes":  "Estamos em teste com os professores"
    },
    {
        "dataPrevista":  "23/02/26",
        "atividades":  "Enviar mensagem aos professores para teste do agendamento",
        "id":  79,
        "status":  "Concluído",
        "assunto":  "Gran Book",
        "area":  "Agendamento",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "09/03/26",
        "atividades":  "Elaborar cronograma para instalação do Google Drive na máquina dos professores",
        "id":  80,
        "status":  "Concluído",
        "assunto":  "Professor não envia vídeo",
        "area":  "Edição",
        "responsavel":  "Filipe",
        "observacoes":  "Se nenhum professor crítico desmarcar conseguiremos concluir dia 19/03"
    },
    {
        "dataPrevista":  "",
        "atividades":  "Concluir instalação do Google Drive na máquina dos professores",
        "id":  81,
        "status":  "Em andamento",
        "assunto":  "Professor não envia vídeo",
        "area":  "Edição",
        "responsavel":  "Filipe e Costinha",
        "observacoes":  "Iremos priorizar os profs que são de fora de Brasília. Equipe do Costinha vai atualizar a planilha de agendamentos e cronograma de prioridades."
    },
    {
        "dataPrevista":  "",
        "atividades":  "Levantar feedbacks de AVB no NPS e pesquisas do Sucesso do Aluno OU solicitar pesquisas direcionadas para concursos, graduação e pós-graduação",
        "id":  82,
        "status":  "",
        "assunto":  "Qualidade",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Criar plano de Manutenção Preventiva das máquinas",
        "id":  83,
        "status":  "",
        "assunto":  "Técnico",
        "area":  "Estúdios presenciais",
        "responsavel":  "André",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Estudar forma de realizar plano de Manutenção Preventiva para máquinas do Home",
        "id":  84,
        "status":  "",
        "assunto":  "Técnico",
        "area":  "Home",
        "responsavel":  "André",
        "observacoes":  "Junto com Walisson (Externa)"
    },
    {
        "dataPrevista":  "23/02/26",
        "atividades":  "Reforçar com os times: Cuidados com gravação Graduação e Pós: evitar erros de ensino superior (operador precisa acompanhar!)",
        "id":  85,
        "status":  "Concluído",
        "assunto":  "Ensino Superior",
        "area":  "Estúdios presenciais",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "23/02/06",
        "atividades":  "Comunicar (IFT): Criar reuniões quinzenais com o time",
        "id":  86,
        "status":  "Concluído",
        "assunto":  "Pessoas",
        "area":  "Liderança",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "23/02/26",
        "atividades":  "Comunicar (IFT): Criar 1:1 mensal com todos do time",
        "id":  87,
        "status":  "Concluído",
        "assunto":  "Pessoas",
        "area":  "Liderança",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Viabilizar uma forma do professor enxergar os próximos slides no estúdio com chroma",
        "id":  88,
        "status":  "",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Estúdios presenciais",
        "responsavel":  "André",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "20/03/26",
        "atividades":  "Levantar o custo mensal com AWS que teríamos se os nossos vídeos no AVA fossem em 4K?",
        "id":  89,
        "status":  "Cancelado",
        "assunto":  "AVA",
        "area":  "Edição",
        "responsavel":  "Filipe",
        "observacoes":  "Teste foi realizado 12/03 e a equipe de TI entendeu que não é viável nesse momento esse projeto."
    },
    {
        "dataPrevista":  "16/03/26",
        "atividades":  "Fazermos levantamento das premissas e fluxo ideal de agendamento / cancelamento",
        "id":  90,
        "status":  "Concluído",
        "assunto":  "Automatização grade",
        "area":  "Agendamento",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Avaliar uso do chroma ou painel",
        "id":  91,
        "status":  "",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Estúdios presenciais",
        "responsavel":  "Rodrigo",
        "observacoes":  "Junto com Rodrigo, André, Walisson e Digão"
    },
    {
        "dataPrevista":  "23/02/26",
        "atividades":  "Campo do uniforme no Saturno deixar como obrigatório",
        "id":  92,
        "status":  "Concluído",
        "assunto":  "Professores",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "12/03/26",
        "atividades":  "Fazer um levantamento sobre as mudança das câmeras dos estúdios (NXR pra FX2), para que o GG entenda melhor, para postar conteúdo em sua rede social",
        "id":  93,
        "status":  "Concluído",
        "assunto":  "Atualização de Equipamentos",
        "area":  "Estúdios presenciais",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "09/03/26",
        "atividades":  "Retornar ao pedagógico sobre Profs Bruno Pet (validação) e Amanda Palácio (comprar kit novo)",
        "id":  94,
        "status":  "Concluído",
        "assunto":  "Professores",
        "area":  "Home",
        "responsavel":  "Costinha",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "16/03/26",
        "atividades":  "Retorno de TI sobre os novos notebooks - compraremos outro ou seguiremos com o mesmo?",
        "id":  95,
        "status":  "Concluído",
        "assunto":  "Atualização de Equipamentos",
        "area":  "Home",
        "responsavel":  "Costinha",
        "observacoes":  "09/03/26: Status troca notebooks Vmix:\n5 máquinas entregues (4 em uso pleno - Renato Borelli, Josimar Padilha, Diego Fontes e Fabiano)\n1 com o prof. Wagner Aguiar apresentando instabilidade (máquina testada previamente; TI validando se é rede ou hardware)\n1 em análise na TI por lentidão e travamento.\n\nPlanejamento novas máquinas:\nAguardando retorno da TI para validar se o modelo atual atende plenamente nosso uso ou se será recomendada alternativa (Lenovo).\nAssim que a máquina retornar da TI, faremos teste de gravação 4K (H265) com nosso kit para validar se suporta eventual migração futura para 4K.\n\n16/03/26: TI retornou que seguiremos com os notebooks comprados, mesmo apresentando alguns problemas."
    },
    {
        "dataPrevista":  "30/04/26",
        "atividades":  "Temos um valor orçado de R$ 14.400 para atualização de Vmix - Definir quais professores faremos a atualização - Deixar um valor separado para atualizar no final do ano os computadores do presencial",
        "id":  96,
        "status":  "Em andamento",
        "assunto":  "Atualização de Equipamentos",
        "area":  "Home",
        "responsavel":  "Costinha",
        "observacoes":  "Vamos priorizar os professores de fora do DF e os prioritários. Deixaremos também um valor para atualizar os computadores do presencial para o final do ano.\nCom esse valor conseguiremos 48 licenças.\nPresencial 15 máquinas (Novembro).\nHome 33 - Abril: 15 / Junho:18"
    },
    {
        "dataPrevista":  "09/03/26",
        "atividades":  "Resolume ??? (7000 previsto em janeiro)",
        "id":  97,
        "status":  "Concluído",
        "assunto":  "Atualização de Equipamentos",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Faremos apenas a atualização do Resolume (R$ 1500) em Março"
    },
    {
        "dataPrevista":  "09/03/26",
        "atividades":  "Comunicar ao time para fazer ajustes nas aulas para erros de português \"grotescos e claros\"",
        "id":  98,
        "status":  "Concluído",
        "assunto":  "PPT",
        "area":  "Diagramação",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "13/03/26",
        "atividades":  "Ajustar o dash de diagramação e fazer o levantamento dos professores que enviam o material em até 24h e 48h",
        "id":  99,
        "status":  "Concluído",
        "assunto":  "Professores",
        "area":  "Diagramação",
        "responsavel":  "Pedro",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "22/05/26",
        "atividades":  "Estudar com o Pedro % ideal de vídeos analisados pela qualidade",
        "id":  100,
        "status":  "Em andamento",
        "assunto":  "Qualidade",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  "Olhamos para 2 normas diferentes, vamos analisar, escolher uma e montar proposta."
    },
    {
        "dataPrevista":  "22/05/26",
        "atividades":  "Desenvolver o novo formato de avaliação de qualidade",
        "id":  101,
        "status":  "",
        "assunto":  "Qualidade",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "20/03/26",
        "atividades":  "Trocar TV do estúdio 3 para touch",
        "id":  102,
        "status":  "Concluído",
        "assunto":  "Técnico",
        "area":  "Estúdios presenciais",
        "responsavel":  "André",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "11/03/26",
        "atividades":  "Solicitar ao Pedro - relatório dos professores que possuem kit próprio e as horas gravadas dos últimos 6 meses",
        "id":  103,
        "status":  "Concluído",
        "assunto":  "Professores",
        "area":  "Home",
        "responsavel":  "Costinha",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "17/03/26",
        "atividades":  "Recolher kit home Profa Pollyana Lyra",
        "id":  104,
        "status":  "Concluído",
        "assunto":  "Professores",
        "area":  "Home",
        "responsavel":  "Costinha",
        "observacoes":  "Recolhido em 17/03/26"
    },
    {
        "dataPrevista":  "17/03/26",
        "atividades":  "Agendar configuração home Profa Lorena O´Campos - se não acontecer até 13/03 comunicar ao pedagógico para recolher o kit home da professora",
        "id":  105,
        "status":  "Concluído",
        "assunto":  "Professores",
        "area":  "Home",
        "responsavel":  "Costinha",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "06/05/26",
        "atividades":  "Identificar oportunidade de melhoria para não termos mais erros de inclusão do link errado quando há dois links criados",
        "id":  106,
        "status":  "Em andamento",
        "assunto":  "Erros",
        "area":  "Estúdios presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Agendado com a coordenadora de Eventos Online dia 06/05, para discutirmos o melhor fluxo de disponibilização de link."
    },
    {
        "dataPrevista":  "23/03/26",
        "atividades":  "Solicitar ao Danilo a criação do botão de \"Liberação Extraordinária\" da OS e o motivo no Saturno",
        "id":  107,
        "status":  "Atrasado",
        "assunto":  "Saturno",
        "area":  "Estúdios presenciais",
        "responsavel":  "Adamin",
        "observacoes":  "30/03: Não foi liberado na última atualização do Saturno / 14/04 Danilo informou que será liberado até o dia 17/04"
    },
    {
        "dataPrevista":  "",
        "atividades":  "Listar melhorias do Saturno e priorizá-las - Ricardo",
        "id":  108,
        "status":  "Em andamento",
        "assunto":  "Saturno",
        "area":  "Saturno",
        "responsavel":  "Adamin",
        "observacoes":  "Adamin terá reunião 31/03 com o Ricardo.\nFoi realizado o levantamento com todos os líderes e o Ricardo priorizará."
    },
    {
        "dataPrevista":  "",
        "atividades":  "Produto: notificar quando o vídeo estiver com áudio ruim - conversar com Camila Meneghetti",
        "id":  109,
        "status":  "",
        "assunto":  "Produto",
        "area":  "Saturno",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "31/05/2026",
        "atividades":  "Treinar o time operacional home",
        "id":  110,
        "status":  "",
        "assunto":  "Padrão Gran Home",
        "area":  "Home",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Produto: notificar quando a aula estiver antiga - conversa com Camila Meneghetti",
        "id":  111,
        "status":  "",
        "assunto":  "Produto",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "16/03/26",
        "atividades":  "Solicitar pesquisa ao Thyago Cevola (UX Research) para entender o melhor formato de aula para a graduação",
        "id":  112,
        "status":  "Concluído",
        "assunto":  "Produto",
        "area":  "Ensino Superior",
        "responsavel":  "Filipe",
        "observacoes":  "Vai gerar a pesquisa a partir do dia 20/03 com o objetivo de saber o que os alunos querem de melhoria nos vídeos"
    },
    {
        "dataPrevista":  "16/03/26",
        "atividades":  "Sugestão de nome para backup do Costinha no lançamento de notas - Comunicar à Lucimara para realizar treinamento",
        "id":  113,
        "status":  "Concluído",
        "assunto":  "Administrativo",
        "area":  "Liderança",
        "responsavel":  "Pryscilla",
        "observacoes":  "Vai ser o Saulo"
    },
    {
        "dataPrevista":  "16/03/26",
        "atividades":  "Dados Profa Flávia Bahia para levar ao Comitê",
        "id":  114,
        "status":  "Concluído",
        "assunto":  "Padrão Gran Home",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "17/03/26",
        "atividades":  "Voltar para H264 todos os vídeos até que seja solucionada a dúvida sobre vídeos em H265",
        "id":  115,
        "status":  "Concluído",
        "assunto":  "Técnico",
        "area":  "Estúdios Presenciais",
        "responsavel":  "André",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "23/03/26",
        "atividades":  "Fazer o levantamento dos professores que enviam o material em até 24h e 48h para enviar ao comitê",
        "id":  116,
        "status":  "Concluído",
        "assunto":  "Professores",
        "area":  "Diagramação",
        "responsavel":  "Rodrigo",
        "observacoes":  "Link com as listas: https://docs.google.com/spreadsheets/d/18LBAVo5MpNubhisL_RyjIrP-lNZ0FKgL/edit?usp=sharing\u0026ouid=113553698903170711726\u0026rtpof=true\u0026sd=true"
    },
    {
        "dataPrevista":  "30/03/26",
        "atividades":  "Planilha de banco de horas: Estão acompanhando??\n\nPrincipais pontos de atenção:\n- Aprovações pendentes: verifiquem se seus liderados possuem pendências de ponto e façam as devidas aprovações. Atentem-se principalmente à existência de banco de horas não autorizado (clique aqui para acessar um manual super completo de aprovação). Importante: batidas não aprovadas pela gestão não são computadas no fechamento!\n\n- Impacto de Horas Positivas: todas as horas positivas do time serão pagas como banco de horas (adicional de 50% + DSR) na folha. Isso vai impactar diretamente o orçamento de cada área; por isso, acompanhem o volume de horas e alinhem compensações por folga antes da data de corte (15/04).\n\n- Regra de Horas Negativas: o desconto em folha só acontece para saldos que ultrapassarem o limite de 50 horas negativas. O desconto será apenas sobre o que exceder esse limite (ex: saldo de -53:25 = desconto de 03:25). Por favor, garantam que o time tenha clareza sobre essa regra.\n\n- Organização do time: orientem para que todas as compensações (folgas ou ajustes de jornada) ocorram impreterivelmente até o dia 15/04/2026.",
        "id":  117,
        "status":  "Concluído",
        "assunto":  "Liderança",
        "area":  "Liderança",
        "responsavel":  "Pryscilla",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "13/04/26",
        "atividades":  "Walisson e Adamin: entender as demandas da secretárias e grade",
        "id":  118,
        "status":  "Concluído",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Walisson",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Levantar os motivos das demandas de agendamento estarem atrasadas",
        "id":  119,
        "status":  "Concluído",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Apresentação do 5x2 atualizada com 44h/semanais",
        "id":  120,
        "status":  "Concluído",
        "assunto":  "Escala",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Status da automatização do agendamento",
        "id":  121,
        "status":  "Em andamento",
        "assunto":  "Automatização agendamento",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  "13/04: Adamin enviar até sexta (17/04) a lista de premissas para o time do Saturno"
    },
    {
        "dataPrevista":  "",
        "atividades":  "Agendar reunião semanal com time do Saturno a partir de 10/04/26 (6ª 10 às 11)",
        "id":  122,
        "status":  "Concluído",
        "assunto":  "Automação agendamento",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "31/03/26",
        "atividades":  "Setar todos os estúdios para entrar a vinheta de \"Mudando vidas em 3, 2, 1...\" de modo que o operador não consiga tirar - Reforço da nossa cultura",
        "id":  123,
        "status":  "Concluído",
        "assunto":  "Padrão Gran Presencial",
        "area":  "Técnica",
        "responsavel":  "André",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "01/04/26",
        "atividades":  "Iniciar em 01/04 o envio de relatório semanal ao Magno sobre os professores contatados e que não retornaram o contato para agendamento",
        "id":  124,
        "status":  "Concluído",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "31/03/26",
        "atividades":  "Iniciar teste colocando no grupo do professores do whatsapp os horários da grade que estão disponíveis",
        "id":  125,
        "status":  "Concluído",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "17/04/26",
        "atividades":  "Levantar os dados de ocupação dos estúdios nos horários de 6:30 às 07:00 e 22:30 às 23:00",
        "id":  126,
        "status":  "Em andamento",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "16/04/26",
        "atividades":  "Novo dashboard da grade e acompanhamento dos professores (relatório)",
        "id":  127,
        "status":  "Em andamento",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "16/04/26",
        "atividades":  "Reunião com as Coordenadoras pedagógicas para apresentação da proposta da quantidade de dias por bloco para gravação e novo fluxo interno da grade",
        "id":  128,
        "status":  "Em andamento",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "08/04/26",
        "atividades":  "Iniciar os testes dos estúdios 2:1",
        "id":  129,
        "status":  "Concluído",
        "assunto":  "Estúdios Presenciais",
        "area":  "Estúdios Presenciais",
        "responsavel":  "Walisson",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "17/04/26",
        "atividades":  "Força tarefa para inclusão do telefone dos professores na planilha",
        "id":  130,
        "status":  "Em andamento",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "24/04/26",
        "atividades":  "Agendamento: automatizar whatsapp para demandas",
        "id":  131,
        "status":  "Em andamento",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  "Está sendo desenvolvido pelo Pedro"
    },
    {
        "dataPrevista":  "17/04/26",
        "atividades":  "Concluir os testes dos estúdios 2:1 (estúdios 6 e 7)",
        "id":  132,
        "status":  "Concluído",
        "assunto":  "Estúdios Presenciais",
        "area":  "Estúdios Presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "https://grancursosonline.atlassian.net/browse/PDA-41?atlOrigin=eyJpIjoiM2VkMDYxNTI2YjZiNGE4NmE4Mjg4NDY0ZWUzMzA5YWYiLCJwIjoiaiJ9"
    },
    {
        "dataPrevista":  "13/04/26",
        "atividades":  "Desenvolver escala 5:2 ",
        "id":  133,
        "status":  "Concluído",
        "assunto":  "Grade",
        "area":  "Grade",
        "responsavel":  "Adamin",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "08/05/26",
        "atividades":  "Levantar vídeos com áudio ruim do Prof Diego Fontes para ajustar e estudar causa raiz do problema - reclamação NPS",
        "id":  134,
        "status":  "",
        "assunto":  "Audio Ruim",
        "area":  "Qualidade",
        "responsavel":  "Rodrigo",
        "observacoes":  ""
    },
    {
        "dataPrevista":  "",
        "atividades":  "Concluir expansão estúdios 2-3 e 8-9",
        "id":  135,
        "status":  "Em andamento",
        "assunto":  "Estúdios Presenciais",
        "area":  "Estúdios Presenciais",
        "responsavel":  "Walisson",
        "observacoes":  "Dia 29/04, incluiremos os estúdios 08 e 09 no 2:1. Com base no bom andamento na operação, irei estipular a data para os estúdios 02 e 03."
    },
    {
        "dataPrevista":  "27/04/26",
        "atividades":  "Limitação de 10 Lives Simultâneas no YouTube",
        "id":  136,
        "status":  "Concluído",
        "assunto":  "Youtube",
        "area":  "Estúdios Presenciais e Home",
        "responsavel":  "Digão",
        "observacoes":  "Em contato com o suporte da YouTube consegumos remover a restrição"
    },
    {
        "dataPrevista":  "29/04/26",
        "atividades":  "Formatação e testes do vMix 1 crashando - Sede 12",
        "id":  137,
        "status":  "Concluído",
        "assunto":  "Estúdios Presenciais",
        "area":  "Estúdios Presenciais",
        "responsavel":  "Digão",
        "observacoes":  "Ticket #167658 - PC realocado no lugar do vMix 2"
    },
    {
        "dataPrevista":  "",
        "atividades":  "vMix 2 Crashando - Sede 12",
        "id":  138,
        "status":  "Em andamento",
        "assunto":  "Estúdios Presenciais",
        "area":  "Estúdios Presenciais",
        "responsavel":  "Digão",
        "observacoes":  "#171611 - Aguardando retorno "
    }
];

const SAMPLE_NOTEBOOKS = [
    {
        "professor":  "Professores",
        "id":  9,
        "modeloAntigo":  "Modelo máquina antiga",
        "horasMes1":  "Horas gravadas Out/25",
        "media3Meses":  "Volume de gravação (Média 3 meses)",
        "localidade":  "Localidade Professor",
        "quantidade":  "Quantidade",
        "situacao":  "Situação notebooks novos",
        "horasMes3":  "Horas gravadas Dez/25",
        "anoMaquina":  "Ano da máquina",
        "horasMes2":  "Horas gravadas Nov/25",
        "kitTipo":  "Kit próprio ou Gran?",
        "checkHardware":  "Chegada da máquina no Gran",
        "notaAvaliacao":  "Nota avaliação professor"
    },
    {
        "professor":  "Renato Borelli",
        "id":  10,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "1",
        "situacao":  "Comprados",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "Concluído",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Diego Fontes",
        "id":  11,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "1",
        "situacao":  "Comprados",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "Concluído",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Fabiano Bordignon",
        "id":  12,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "São Paulo",
        "quantidade":  "1",
        "situacao":  "Comprados",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "Concluído",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Geilza Diniz",
        "id":  13,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "1",
        "situacao":  "Comprados",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "Concluído",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Josimar Padilha",
        "id":  14,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "1",
        "situacao":  "Comprados",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "Concluído",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Wagner Aguiar",
        "id":  15,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Bahia",
        "quantidade":  "1",
        "situacao":  "Comprados",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "Concluído",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Andrey Soares",
        "id":  17,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Montes Claros / MG",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Cristiny Mroczkoski",
        "id":  18,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Porto Alegre / RS",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Diego Ribeiro",
        "id":  19,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Igor Goulart",
        "id":  20,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Argentina /ARG",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "José Wesley",
        "id":  21,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Leonardo Albernaz",
        "id":  22,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Nestor Távora",
        "id":  23,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Rio de Janeiro /RJ",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2019",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Alexandre Meirelles",
        "id":  24,
        "modeloAntigo":  "Dell G3",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "São Paulo / SP",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "André Martini",
        "id":  25,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Goiânia / GO",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Aragonê Fernandes",
        "id":  26,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Cid Roberto",
        "id":  27,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Claiton Natal",
        "id":  28,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Dermeval Farias",
        "id":  29,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Douglas Gomes",
        "id":  30,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Eduardo Galante",
        "id":  31,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Divisópolis / MG",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Érico Palazzo",
        "id":  32,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Fernando Maciel",
        "id":  33,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Gustavo Scatolino",
        "id":  34,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Jeferson Bogo",
        "id":  35,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "José Filho",
        "id":  36,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "?",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "José Gevásio Meireles",
        "id":  37,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Juliana Auad",
        "id":  38,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Canadá / CA",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Júlio Santos",
        "id":  39,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Karinne Figueiredo",
        "id":  40,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Leonardo Murga",
        "id":  41,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Lidia Marangon",
        "id":  42,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Lorena Ocampos",
        "id":  43,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Lorraine Bonadio",
        "id":  44,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Marcelo Leite",
        "id":  45,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Maria Christina",
        "id":  46,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Mauricio Franceschini",
        "id":  47,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Natale Souza",
        "id":  48,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Salvador / BA",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Nilton Coutinho",
        "id":  49,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "São Paulo / SP",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Paulo Kuririn",
        "id":  50,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "?",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Pollyana Lyra",
        "id":  51,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Rafael Vieira",
        "id":  52,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Ricardo Blanco",
        "id":  53,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Rodrigo Cardoso",
        "id":  54,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Sérgio Carvalho",
        "id":  55,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Fortaleza / CE",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    },
    {
        "professor":  "Valcir Spanholo",
        "id":  56,
        "modeloAntigo":  "Dell G5",
        "horasMes1":  "",
        "media3Meses":  "",
        "localidade":  "Brasília / DF",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "quantidade":  "",
        "situacao":  "",
        "horasMes3":  "",
        "anoMaquina":  "2020",
        "horasMes2":  "",
        "kitTipo":  "",
        "checkHardware":  "",
        "notaAvaliacao":  ""
    }
];

function initializeData() {
  if (!localStorage.getItem('avb_initialized')) {
    localStorage.setItem('avb_users', JSON.stringify(DEFAULT_USERS));
    localStorage.setItem('avb_demandas', JSON.stringify(SAMPLE_DEMANDAS));
    localStorage.setItem('avb_notebooks', JSON.stringify(SAMPLE_NOTEBOOKS));
    localStorage.setItem('avb_history', JSON.stringify([]));
    localStorage.setItem('avb_initialized', 'true');
  }
}